# start with a clean environment
rm(list=ls())

old_dir <- getwd()
setwd("/Users/jmmg57/coursera/ExData_Plotting1")
df <- read.csv("household_power_consumption.txt",sep = ";")
df$Date <- as.Date(df$Date, format="%d/%m/%Y")
df <- df[(df$Date=="2007-02-01") | (df$Date=="2007-02-02"),]
df$Global_active_power <- as.numeric(df$Global_active_power)/1000
df$Voltage <- as.numeric(df$Voltage)
df$Sub_metering_1 <- as.numeric(df$Sub_metering_1)
df$Sub_metering_2 <- as.numeric(df$Sub_metering_2)
df$Sub_metering_3 <- as.numeric(df$Sub_metering_3)
df <- transform(df, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
quartz()
par(mfrow=c(2,2))
plot(df$timestamp,df$Global_active_power, type="l", xlab="", ylab="Global Active Power")
# axis(1,at=axTicks(1), labels=paste(axTicks(1)/1000,sep=""))
# axis(2, at=axTicks(2), labels=paste(axTicks(2)/1000sep=""))
plot(df$timestamp,df$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(df$timestamp,df$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(df$timestamp,df$Sub_metering_2,col="red")
lines(df$timestamp,df$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(df$timestamp,df$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()
setwd(old_dir)